### ISSUE TITLE
Fix to use proper p_name at some point

### ISSUE THREAD

**Issue by arturo182** [xil-se/xildebug_sw#5]
https://github.com/xil-se/xildebug_sw/blob/b5ef8b66cc7f98fa468062f20203c5f07501058a/app/drivers/adc.c#L51

https://github.com/xil-se/xildebug_sw/blob/b5ef8b66cc7f98fa468062f20203c5f07501058a/app/drivers/adc.c#L65

**Comment by kbeckmann** [comment]
You mean change the argument names to p_adc_handle or something? I think we might have a lot of these in the whole codebase.

**Comment by arturo182** [comment]
Yeah, exactly what I meant, and move the asterisk to the right, need to follow them kernel style rules ;)

**Comment by kbeckmann** [comment]
To be honest, the functions that have this issue are functions that are declared in the SDK. Changing argument names feels a bit so-so, they should ideally match with the .h file.
