### ISSUE TITLE
Check if i2c handle is initialized

### ISSUE THREAD

**Issue by arturo182** [xil-se/xildebug_sw#6]
https://github.com/xil-se/xildebug_sw/blob/b5ef8b66cc7f98fa468062f20203c5f07501058a/app/drivers/i2c.c#L61

https://github.com/xil-se/xildebug_sw/blob/b5ef8b66cc7f98fa468062f20203c5f07501058a/app/drivers/i2c.c#L66

**Comment by kbeckmann** [comment]
Sure. But before that, I think we should decide on an error strategy other than HAL_StatusTypeDef

**Comment by arturo182** [comment]
So my idea is to have a errors.h file with base defines per module and then in each module have custom error codes using the base + 1, 2, 3, etc. This way each module gets unique errors :)

**Comment by kbeckmann** [comment]
Ok I can fix it.
