### ISSUE TITLE
Pointer vs array

### ISSUE THREAD

**Issue by arturo182** [xil-se/xildebug_sw#8]
Didn't you mean *p_val and not p_val[0].

Also we should check p_val for NULL.

https://github.com/xil-se/xildebug_sw/blob/b5ef8b66cc7f98fa468062f20203c5f07501058a/app/drivers/max14662.c#L83

**Comment by kbeckmann** [comment]
Sure

**Comment by kbeckmann** [comment]
Again, error. should i return HAL_ERROR?

**Comment by simonvik** [comment]
Use 0[p_val]  instead to increase readability!

**Comment by kbeckmann** [comment]
> Use 0[p_val] instead to increase readability!

You are now a moderator of /r/ioccc
